'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Stargate_Simulator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Milky_Way_stargate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Milky_Way_stargate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilkyWayGlyph39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilkyWayGlyph39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
